### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by aknuds1** [leebenson/babel-preset-node5#1]
I am unable to install babel-preset-node5 with Node 5.1.0 on OS X. What happens is this:
```
➜  muzhack git:(serverside) npm install --save-dev babel-preset-node5
npm ERR! Darwin 13.4.0
npm ERR! argv "/Users/arve/.nvm/versions/node/v5.1.0/bin/node" "/Users/arve/.nvm/versions/node/v5.1.0/bin/npm" "install" "--save-dev" "babel-preset-node5"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code EREADFILE

npm ERR! Error extracting /Users/arve/.npm/babel-preset-node5/6.1.4/package.tgz archive: ENOENT: no such file or directory, open '/Users/arve/.npm/babel-preset-node5/6.1.4/package.tgz'
```

**Comment by leebenson** [comment]
@aknuds1 please try again. If that doesn't work, try these two commands:

`npm cache clean`
`npm i -D babel-preset-node@6.2.1`

It looks like NPM 3 has an issue with versions that include a hyphen. It turned version 6.1.20-3 into 6.1.4, and so it couldn't find `package.tgz` at that path.

I've bumped the version to reflect the latest babel-core so this _should_ fix it. Let me know if you have any other issues.

**Comment by aknuds1** [comment]
I don't understand, why `babel-preset-node` as opposed to `babel-preset-node5`? These are two different packages are they not?

**Comment by aknuds1** [comment]
I installed `babel-preset-node` instead FWIW, since that was installable.

**Comment by leebenson** [comment]
Typo! Fixed.

This package adds a few extra fixtures vs `babel-preset-node` - I'd recommend this one for more complete coverage.

**Comment by aknuds1** [comment]
Somehow `npm install --save-dev babel-preset-node5` worked now.

**Comment by leebenson** [comment]
Yeah, should all be fixed now. Let me know if you run into any other issues.
