### ISSUE TITLE
Add transform-es2015-spread?

### ISSUE THREAD

**Issue by pieterv** [leebenson/babel-preset-node5#10]
Looks like [node > 5.x will support spread](https://nodejs.org/en/docs/es6/#which-features-ship-with-node-js-by-default-no-runtime-flag-required) but its not added here. Is it worth adding [transform-es2015-spread](http://babeljs.io/docs/plugins/transform-es2015-spread/)?

**Comment by leebenson** [comment]
@pieterv the aim of `babel-preset-node5` is to target/augment Node 5.x functionality, so anything that is already implemented natively doesn't require a polyfill.

[transform-es2015-spread](http://babeljs.io/docs/plugins/transform-es2015-spread/) is useful for Node 4.x, but is outside the scope of this preset.

**Comment by pieterv** [comment]
My understanding was Node 4.x doesn't support spread natively but Node 5.x should/will support it, is that not the aim of this preset?

**Comment by pieterv** [comment]
Oh right i understand now, i was under the impression that this repo was designed to bridge the gap between Node <= 4.x -> Node 5.x, not to add features on top of Node 5.x. Sorry for the confusion!

**Comment by leebenson** [comment]
np!
