### ISSUE TITLE
Node v6 coming out soon!

### ISSUE THREAD

**Issue by seeekr** [leebenson/babel-preset-node5#11]
Just in case you're interested and have missed this: Node v6 is coming out Tuesday next week (26th), and currently RC 3 is being released. There's 93% ES2015 support in v6, 96% if you run with `--es-staging` flag.
So in case you'd like to get a preset out for node6, I think that'd come in handy for those of us who're going to jump onto v6 really early!
Cheers,
Denis

EDIT: Forgot to link this: [nodejs/node: planning for v6](https://github.com/nodejs/node/issues/5766#issuecomment-211901937)

**Comment by mgol** [comment]
Someone has already published the relevant package: https://www.npmjs.com/package/babel-preset-es2015-node6

**Comment by Salakar** [comment]
That'd be me =] updated readme with more info. It's based on today's rc.3 release.

**Comment by seeekr** [comment]
Wow, this community is on top of things! Thanks guys, this is awesome! I'll leave this issue open for this project's maintainer to decide what to do with it :) But from my perspective it can be closed, I definitely found what I was looking for!

**Comment by leebenson** [comment]
Good work @seeekr - I'll link to your repos in the readme and continue to maintain node5 for a while, at least until v6 hits stable release.
