### ISSUE TITLE
Add as part of a env preset

### ISSUE THREAD

**Issue by hzoo** [leebenson/babel-preset-node5#12]
Would you be interested in adding this or just helping out in a community effort to make Babel have a single preset for all environments? More details in my PR https://github.com/babel/babel/pull/3476. The basic idea is to pass in what version/envs you want to support and it would return the relevant plugins based on the least common denominator.

Basically we would just add the necessary plugins for each environment (chrome, node 4/5/6, etc) in the file and then write some logic to determine the output.

Maybe I should just ping people in the PR rather than making an issue in each one..

**Comment by leebenson** [comment]
@hzoo I think it's a great idea. Looks like there are plenty of takers already at babel/babel#3476 contributing ideas/code, so I'll bow out of the thread for now but will watch the efforts closely.

**Comment by hzoo** [comment]
@leebenson would you be cool with deprecating the babel-preset-nodex presets? I'd like for the community to start using https://github.com/babel/babel-preset-env now (which what the PR ^ became).

This could mean adding "deprecated" and linking to the repo in the readme and running something like `npm deprecate 'message'` from the command line if you're up for it.

Basically instead of having to make a new preset each node release, we would just update env. 

```
{
  "presets": [
    ["env", {
      "targets": {
        "node": "current"
      }
    }]
  ]
}
```

**Comment by leebenson** [comment]
Sure @hzoo, happy to direct users to the latest best practice. I'll get it done today.

**Comment by hzoo** [comment]
Awesome, thanks for making these for people to use in the meantime - I just realized that it was getting crazy with all the combinations of preset-nodex-, chrome-55, w.e presets when it really wasn't necessary.

**Comment by leebenson** [comment]
my pleasure... your new direction is definitely the way to go, good work!

**Comment by leebenson** [comment]
@hzoo - just an FYI that I deprecated this just now. Will do the same for the [node7] preset too.
