### ISSUE TITLE
Ability to pass moduleTypes like babel-preset-2015

### ISSUE THREAD

**Issue by ngryman** [leebenson/babel-preset-node5#13]
Hey,

I would like to use your preset with `rollup`. To do that I need to let `rollup` handle modules. As your preset includes `babel-plugin-transform-es2015-modules-commonjs` by default, it conflicts with `rollup`.

`babel-preset-2105` allows the user to choose the module type he wants or disable module transpilation. It would be awesome if your preset could support this:

```json
{
  "presets": [
    ["node5", { "modules": false }]
  ]
}
```

Here is how they do it: https://github.com/babel/babel/blob/master/packages/babel-preset-es2015/src/index.js#L34.

Thanks!

**Comment by leebenson** [comment]
Great idea @ngryman. This would be useful for Webpack 2 tree-shaking, too. I'll try to post a new version with it featured this week. If you need it faster, I'd happily accept a PR, too. Cheers!

**Comment by ngryman** [comment]
Are you working on it, I have some spare today and tomorrow if you want 👍

**Comment by leebenson** [comment]
@ngryman - I haven't started yet, so if you've got the time, feel free! Thanks!

**Comment by ngryman** [comment]
PR is sitting here btw: #14.
