### ISSUE TITLE
Remove react dependency?

### ISSUE THREAD

**Issue by jzaefferer** [leebenson/babel-preset-node5#2]
I like this preset for its plugin list (and wouldn't want to maintain that myself), but since my node app doesn't use react, having the react preset in there makes the whole thing a bit pointless. Would you consider dropping the react preset and making this just a list of plugins? It seems like any app using react can just add the react preset directly (its a preset after all).

PS: A few lines of usage instructions would be nice as well, since the babel docs are pretty sparse on using presets

**Comment by leebenson** [comment]
@jzaefferer I see your point. Good idea. I'll drop it and add usage instructions. Thanks!

**Comment by jzaefferer** [comment]
While you're on it, the "ES2015 preset" link in the README (under Motivation) doesn't work.

**Comment by leebenson** [comment]
Fixed in e27518f1951481983fd9614d39cc372710810893. Published new version on NPM. Should be good to go.
