### ISSUE TITLE
for...of inside generator function causes transpilation failure

### ISSUE THREAD

**Issue by HowlingEverett** [leebenson/babel-preset-node5#4]
This is a known dependency for the regenerator library: https://github.com/facebook/regenerator/issues/229

Basically `babel-plugin-transform-regenerator` requires `babel-plugin-transform-es2015-for-of` to recognise the `ForOfStatement` AST symbol. Without it, when you place a for...of inside a generator function, transpilation fails with the error

```
unknown Statement of type "ForOfStatement"
```

Node 5.0+ has native support for generator functions, so I'm guessing that the reason `babel-preset-node5` needs it is as a foundation for async/await ES7 stuff? I'd prefer to get that working separately if necessary, and remove `transform-regenerator` from this preset.

Otherwise, it's necessary to include `transform-es2015-for-of` as a plugin before `transform-regenerator` to handle for this (fairly common) edge case.

**Comment by leebenson** [comment]
Thanks for flagging this.

You're right - we don't need `transform-regenerator` at all. I was using the plug-in with webpack to target the browser, since we want to bypass generators entirely. This can be swapped out for `transform-async-to-generator` in Node 5.

With this source code:

```
const obs = [1,2,3];

async function test() {
  for (let val of obs) {
    await new Promise(ok => {
      setTimeout(()=> {
        ok(console.log(val));
      }, 1000);
    });
  }
}
test().then(()=> {
  console.log('done');
});

```

... `transform-regenerator` produced this error:

```
Error: test.js: unknown Statement of type "ForOfStatement"
    at Emitter.Ep.explodeStatement (/Users/leebenson/dev/babel-preset-node5/node_modules/babel-plugin-transform-regenerator/lib/emit.js:648:13)
    at /Users/leebenson/dev/babel-preset-node5/node_modules/babel-plugin-transform-regenerator/lib/emit.js:342:12
    at Array.forEach (native)
    at Emitter.Ep.explodeStatement (/Users/leebenson/dev/babel-preset-node5/node_modules/babel-plugin-transform-regenerator/lib/emit.js:341:22)
    at Emitter.Ep.explode (/Users/leebenson/dev/babel-preset-node5/node_modules/babel-plugin-transform-regenerator/lib/emit.js:296:40)
    at PluginPass.exit (/Users/leebenson/dev/babel-preset-node5/node_modules/babel-plugin-transform-regenerator/lib/visit.js:106:15)
    at newFn (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/visitors.js:276:19)
    at NodePath._call (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/context.js:116:8)
```

(which I believe is where the `for...of` issue came in - although it seems that adding `transform-runtime` to the plug-in list can solve it, as an FYI for those that still need it to target the browser).

Now, swapping it out for `transform-async-to-generator` generates the following instead:

```
'use strict';

function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { var callNext = step.bind(null, "next"); var callThrow = step.bind(null, "throw"); function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { Promise.resolve(value).then(callNext, callThrow); } } callNext(); }); }; }

const obs = [1, 2, 3];

let test = (function () {
  var ref = _asyncToGenerator(function* () {
    for (let val of obs) {
      yield new Promise(function (ok) {
        setTimeout(() => {
          ok(console.log(val));
        }, 1000);
      });
    }
  });

  return function test() {
    return ref.apply(this, arguments);
  };
})();

test().then(() => {
  console.log('done');
});
```

... which runs fine.

I'll get the package updated and pushed to NPM today.

**Comment by HowlingEverett** [comment]
:100: :) Thanks.
