### ISSUE TITLE
Include Array.includes to the preset

### ISSUE THREAD

**Issue by fl0w** [leebenson/babel-preset-node5#7]
How would you feel about including [Array.includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) via [babel-plugin-array-includes](https://www.npmjs.com/package/babel-plugin-array-includes)?

Not an issue adding this myself, I just enjoyed the idea for a preset like this and would prefer a decent bundle.

**Comment by leebenson** [comment]
I'm open to adding any missing features, but that particular plugin is dangerous -- https://github.com/stoeffel/babel-plugin-array-includes/issues/1#issuecomment-165704493

Example:

```
const test = {
  includes() {
    console.log('should print to console');
  },
};

test.includes();
```

Which produces: 

> should print to console

... transpiles to:

```
const test = {
  includes() {
    console.log('should print to console');
  }
};

test.indexOf() !== -1;
```

... which produces:

> TypeError: test.indexOf is not a function

In the meantime, I think it's better to use the `--es_staging` flag [mentioned here](https://nodejs.org/en/docs/es6/#which-features-are-behind-the-es_staging-flag) to guarantee no existing `includes` property is accidentally overwritten.
